cy43_ref_iceland:

  file_templates : ['fc%Y%m%d%H+%LLLgrib','fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib_fp']

  atos:
     path_template : 'ec:/icd/DEODE/cy43_ref_iceland/%Y/%m/%d/%H/'

  domain : 
     name : 'ICELAND'
     resolution : 2500
     levels : 65
