NL25_Eunice_n0: 

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/nkac/harmonie/NL25_Eunice_n0/%Y/%m/%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 2500
     levels : 90

NL13_Eunice_n1: 

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/nkac/harmonie/NL13_Eunice_n1/%Y/%m/%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 1300
     levels : 90

NL750_Eunice_n2: 

  file_templates : ['fc%Y%m%d%H+%LLLh%LMmgrib_sfxs','fc%Y%m%d%H+%LLLh%LMmgrib2_fp']

  atos:
     path_template : 'ec:/nkac/harmonie/NL750_Eunice_n2/%Y/%m/%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 750
     levels : 90

NL25_Eunice_n0_NOWFP: 

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/nkac/harmonie/NL25_Eunice_n0_NOWFP/%Y/%m/%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 2500
     levels : 90

NL13_Eunice_n1_NOWFP: 

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/nkac/harmonie/NL13_Eunice_n1_NOWFP/%Y/%m/%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 1300
     levels : 90

NL750_Eunice_n2_NOWFP: 
  file_templates : ['fc%Y%m%d%H+%LLLh%LMmgrib_sfxs','fc%Y%m%d%H+%LLLh%LMmgrib2_fp']

  atos:
     path_template : 'ec:/nkac/harmonie/NL750_Eunice_n2_NOWFP/%Y/%m/%d/%H/'

  domain : 
     name : 'NETHERLANDS'
     resolution : 750
     levels : 90

