deode_cy46ref:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/smb/harmonie/deode_cy46ref/%Y/%m/%d/%H/'

  lumi_transfer:
     path_template : '/scratch/project_462000140/de_33050_common_data/cases/gavle_2021/deode_cy46ref/%Y/%m/%d/%H/'

  domain : 
     name : 'METCOOP25D'
     resolution : 2500
     levels : 65

deode_cy46750:

  file_templates : ['fc%Y%m%d%H+%LLLgrib_sfxs','fc%Y%m%d%H+%LLLgrib2_fp']

  atos:
     path_template : 'ec:/smb/harmonie/deode_cy46750/%Y/%m/%d/%H/'

  domain : 
     name : 'SOMETHING'
     resolution : 750
     levels : 65
